import { type BiggerReactorsReactorData } from '@/types/reactord'

export const defaultBiggerReactor: BiggerReactorsReactorData = {
  active: false,
  ambientTemperature: 0,
  apiVersion: null,
  burnedLastTick: 0,
  capacity: 0,
  casingTemperature: 0,
  coldFluidAmount: 0,
  connected: false,
  controlRodCount: 0,
  coolantCapacity: 0,
  fuel: 0,
  fuelCapacity: 0,
  fuelReactivity: 0,
  fuelTemperature: 0,
  hotFluidAmount: 0,
  maxTransitionedLastTick: 0,
  producedLastTick: 0,
  stackTemperature: 0,
  stored: 0,
  totalReactant: 0,
  transitionedLastTick: 0,
  type: 'none',
  wasteCapacity: 0,
}
